import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  console.log(data);

  return (
    <>
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <h1>isto é o site de DW.</h1>
  </>
        
  )
}

export async function getServerSideProps(context) {
  const res = await fetch('http://teste-projeto-dw.local//wp-json/wp/v2/conto');
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    }
  }
  return {
    props: {
      data
    },
  }
}